preset = {
    "START_GREETINGS": "Хорошей тренировки!",
    "START_START_BUTTON": "Начать",
    "START_SETTING_BUTTON": "Настройки",
    "TRAININGS_HEADER": "Что тренируем сегодня?",
    "TRAININGS_ADD_TRAINING": "Добавить тренировку",
    "TRAININGS_ADD_PLACEHOLDER": "Название тренировки",
    "TRAININGS_ADD_SET_X_REP": "Подходы X Повторения",
    "TRAININGS_ADD_TIME": "Время",
    "TRAININGS_ADD_MODAL": "Упражнение",
    "TRAININGS_ADD_MODAL_TITLE": "Название упражнения: ",
    "TRAININGS_ADD_MODAL_TYPE": "Тип упражнения: ",
    "TRAININGS_ADD_MODAL_SETS": "Подходы: ",
    "TRAININGS_ADD_MODAL_REPS": "Повторения: ",
    "TRAININGS_ADD_MODAL_TIME": "Время (секунды): ",
    "TRAININGS_ADD_MODAL_ADD_BUTTON": "Добавить",
    "TRAININGS_ADD_MODAL_CANCEL_BUTTON": "Назад",
    "TRAININGS_ADD_PICK_IMAGE": "Выбрать фото",
    "TRAININGS_ADD_SET_DEFAULT_IMAGE": "По умолчанию",
    "SETTINGS_HEADER": "Настройки",
    "SETTINGS_LANG_TITLE": "Язык: ",
}